name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  qa-and-tests:
    runs-on: ubuntu-latest

    env:
      HYPOTHESIS_PROFILE: ci

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry
        run: pip install poetry

      - name: Cache Poetry virtualenv
        uses: actions/cache@v4
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        run: poetry install --no-interaction

      # ---- Quality gates ----
      - name: Ruff (lint)
        run: poetry run ruff check .

      - name: Black (check)
        run: poetry run black --check .

      - name: mypy (type-check)
        run: poetry run mypy .

      # ---- Tests + Coverage ----
      - name: Pytest (with coverage)
        run: poetry run pytest -v --cov=src/crew_estimator --cov-report=xml

      # ---- Coveralls upload ----
      - name: Coveralls
        uses: coverallsapp/github-action@v2
        with:
          file: coverage.xml
          format: cobertura
          github-token: ${{ secrets.GITHUB_TOKEN }}

